### ISSUE TITLE
Tofu Delight 1.1.0 causing a crash

### ISSUE THREAD

**Issue by Ross2750** [baguchan/TofuDelight#2]
Hi, I install this mod and after i load minecraft it causes a crash with error code -1

And while i was looking on the crash log i found this error:
`Caused by: java.lang.NullPointerException: Registry Object not present: tofudelight:tofu_metal_cooking_pot`
It looks like it causes a crash because of the metal cooking pot

**Comment by baguchi** [comment]
fixed in newer version!
