### ISSUE TITLE
TofuDelight Crashed at mod loading stage

### ISSUE THREAD

**Issue by BILLYx1120** [baguchan/TofuDelight#3]
**What happened**: TofuDelight cannot load during the loading stage.

**Environments**: Java17, Windows 10, Minecraft 1.19.2, A stable version of Forge, and a third-party Minecraft Loader PCL2 (Which has no effects on the mod loading and helps produce the crash report)

**Here are the packages that contain the Minecraft booting logs**:
    This one with all the mods run together and conflicts with another mod "Neapolitan": 
[tofuDelight错误报告-2023-9-7_17.08.50.zip](https://github.com/baguchan/TofuDelight/files/12553524/tofuDelight.-2023-9-7_17.08.50.zip)
    This one with only farmersDelight and TofuCraftReload and still crashing:
[tofuDelight错误报告-2023-9-7_17.15.31.zip](https://github.com/baguchan/TofuDelight/files/12553534/tofuDelight.-2023-9-7_17.15.31.zip)

As you should have realized these file names contain Chinese, But inside they are still in English and will not make any difficulty reading.

**Comment by baguchi** [comment]
sorry for late. 1.19.2 is no longer support.
If you want. please use newer version such as 1.20.1 and 1.21.1
